/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
'use client'

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function ModernKitchen (props) {

  const kitchenRef = useRef()
  const { nodes, materials } = useGLTF("/models/modern_kitchen.glb")

  return (
    <group ref={kitchenRef} {...props} dispose={null} position={[-0.06, -0.24, -0.2]} scale={0.1}>
      <group position={[-2.808, 1.776, -4.461]} scale={9.12}>
        <group position={[0.253, 0.007, 0.592]} scale={0.09}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Houseplant_7_1.geometry}
              material={materials.Black}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Houseplant_7_2.geometry}
              material={materials.Brown}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Houseplant_7_3.geometry}
              material={materials.Plant_Green}
            />
          </group>
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ScythianAntique.geometry}
          material={materials.M_Gold}
          rotation={[-Math.PI / 2, 0, Math.PI]}
        />
      </group>
      <group position={[-3.641, 0, 6.65]} rotation={[Math.PI, 0, Math.PI]} scale={1.456}>
        <group position={[0, -0.126, 0.025]} rotation={[-Math.PI / 2, 0, 0]} scale={113.589}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Desk_1.geometry}
            material={materials.DarkWood}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Desk_2.geometry}
            material={materials.Wood}
          />
        </group>
        <group position={[0.617, 0.781, -0.001]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Desk_Drawer1_1.geometry}
            material={materials.DarkWood}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Desk_Drawer1_2.geometry}
            material={materials.Wood}
          />
        </group>
        <group position={[0.617, 0.617, -0.002]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Desk_Drawer2_1.geometry}
            material={materials.DarkWood}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Desk_Drawer2_2.geometry}
            material={materials.Wood}
          />
        </group>
        <group position={[-0.617, 0.781, -0.001]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Desk_Drawer3_1.geometry}
            material={materials.DarkWood}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Desk_Drawer3_2.geometry}
            material={materials.Wood}
          />
        </group>
        <group position={[-0.617, 0.617, -0.002]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Desk_Drawer4_1.geometry}
            material={materials.DarkWood}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Desk_Drawer4_2.geometry}
            material={materials.Wood}
          />
        </group>
        <group position={[-0.522, -0.126, 1.181]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.483}>
          <group position={[-1.376, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={90.093}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Couch_Small1_1.geometry}
              material={materials['Couch_Blue.001']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Couch_Small1_2.geometry}
              material={materials['Black.003']}
            />
          </group>
        </group>
        <group position={[-0.349, 0, 4.775]} rotation={[-Math.PI, 0, -Math.PI]} scale={2.07}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.rugRound_2.geometry}
            material={materials.carpet}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.rugRound_2_1.geometry}
            material={materials.carpetDarker}
          />
        </group>
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={materials.Floor2}
        position={[13.187, -0.095, -0.358]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane001.geometry}
        material={materials.Wall0}
        position={[8.812, -0.095, -2.729]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane002.geometry}
        material={materials.Wall1}
        position={[11, -0.095, -2.808]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane003.geometry}
        material={materials.Wall2}
        position={[13.318, -0.095, -2.703]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane004.geometry}
        material={materials.Floor1}
        position={[10.841, -0.095, -0.305]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane005.geometry}
        material={materials.Floor0}
        position={[8.541, -0.095, -0.208]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane006.geometry}
        material={materials.Chair0}
        position={[8.607, -0.095, -5.273]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane007.geometry}
        material={materials.Chair1}
        position={[11, -0.095, -5.39]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane008.geometry}
        material={materials.Chair2}
        position={[13.187, -0.095, -5.284]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane009.geometry}
        material={materials.Cupboard0}
        position={[8.569, -0.095, -7.574]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane010.geometry}
        material={materials.Cupboard1}
        position={[10.906, -0.095, -7.822]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane011.geometry}
        material={materials.Cupboard2}
        position={[13.187, -0.095, -8.091]}
      />
      <group scale={0.01}>
        <group
          position={[-51.067, 80.144, 119.451]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={[100, 370, 980]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Fridge_Counter_0.geometry}
            material={materials.material_0}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Fridge_FridgeGlass_0.geometry}
            material={materials.FridgeGlass}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Fridge_FridgeInside_0.geometry}
            material={materials.FridgeInside}
          />
        </group>
        <group
          position={[599.392, 190.633, 63.681]}
          rotation={[Math.PI / 2, -Math.PI / 2, 0]}
          scale={[5.354, 4.819, 8.923]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Hob_Hob_0.geometry}
            material={materials.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Hob_Material_0.geometry}
            material={materials['Material.001']}
          />
        </group>
        <group
          position={[491.452, 317.41, -361.269]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={[113.73, 90, 1331.953]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Ovens_Handles_0.geometry}
            material={materials.Handles}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Ovens_Hob_0.geometry}
            material={materials.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Ovens_Oven_0.geometry}
            material={materials.Oven}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Ovens_OvenClock_0.geometry}
            material={materials.OvenClock}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Ovens_OvenWindow_0.geometry}
            material={materials.OvenWindow}
          />
        </group>
        <group
          position={[658.811, 205.109, -71.041]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={17.111}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SmallPlant_Bark_0.geometry}
            material={materials.Bark}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SmallPlant_Plant_0.geometry}
            material={materials.Plant}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SmallPlant_Pot_0.geometry}
            material={materials.material_16}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Ceiling_Ceiling_0.geometry}
          material={materials.Ceiling}
          position={[85.764, -27.155, 29.602]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={[514.8, 475.2, 8.712]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Counters_Counter_0.geometry}
          material={materials.material_0}
          position={[599.392, 183.95, 167.541]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cupboard.geometry}
          material={materials.Cupboard2}
          position={[-51.067, 80.144, 119.451]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={[100, 370, 980]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Floor.geometry}
          material={materials.Floor1}
          position={[85.764, -27.155, 29.602]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={[514.8, 475.2, 8.712]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Lightbulbs_Lights_0.geometry}
          material={materials.Lights}
          position={[0, 430.618, -80.549]}
          rotation={[Math.PI / 2, -Math.PI / 2, 0]}
          scale={[5.158, 5.6, 8]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.LightsGlass_LightGlass_0.geometry}
          material={materials.LightGlass}
          position={[0, 404.128, 119.451]}
          rotation={[Math.PI / 2, -Math.PI / 2, 0]}
          scale={[6.447, 7, 10]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.LightSupport_Chrome_0.geometry}
          material={materials.Chrome}
          position={[0, 491.905, 119.451]}
          rotation={[Math.PI / 2, -Math.PI / 2, 0]}
          scale={[6.447, 7, 10]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sink_Sink_0.geometry}
          material={materials.Sink}
          position={[635.665, 198.4, 298.595]}
          rotation={[Math.PI / 2, -Math.PI / 2, 0]}
          scale={[4.118, 4.118, 6.864]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stairs_Stairs_0.geometry}
          material={materials.Stairs}
          position={[724.871, -2.231, 611.403]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={[514.8, 475.2, 8.712]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Chair.geometry}
          material={materials.Chair2}
          position={[-164.325, 131.012, 119.451]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={[40, 40, 3.36]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tiles_Tiles_0.geometry}
          material={materials.Tiles}
          position={[85.764, -27.155, 29.602]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={[514.8, 475.2, 8.712]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Trim_CupboardTrim_0.geometry}
          material={materials.CupboardTrim}
          position={[-51.067, 80.144, 119.451]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={[100, 370, 980]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Window_Window_0.geometry}
          material={materials.Window}
          position={[85.764, -27.155, 29.602]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={[514.8, 475.2, 8.712]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WindowTrim_CupboardTrim_0.geometry}
          material={materials.CupboardTrim}
          position={[85.764, -27.155, 29.602]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={[514.8, 475.2, 8.712]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wall.geometry}
          material={materials.Wall0}
          position={[85.764, -27.155, 29.602]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={[514.8, 475.2, 8.712]}
        />
      </group>
      <group position={[-3.26, -0.216, -3.339]} rotation={[-Math.PI / 2, 0, 0]} scale={74.221}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Couch_Medium1_1.geometry}
          material={materials.Couch_Blue}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Couch_Medium1_2.geometry}
          material={materials['Black.001']}
        />
      </group>
      <group position={[-0.297, 1.892, 0.27]} scale={1.455}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Houseplant_4_1.geometry}
            material={materials['Black.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Houseplant_4_2.geometry}
            material={materials['Brown.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Houseplant_4_3.geometry}
            material={materials['Plant_Green.001']}
          />
        </group>
      </group>
    </group>
  )
}


useGLTF.preload('/models/modern_kitchen.glb');
